# Makefile.in generated by automake 1.14.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/libopencif
pkgincludedir = $(includedir)/libopencif
pkglibdir = $(libdir)/libopencif
pkglibexecdir = $(libexecdir)/libopencif
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
subdir = .
DIST_COMMON = INSTALL NEWS README AUTHORS ChangeLog \
	$(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	$(srcdir)/config.h.in depcomp $(nobase_include_HEADERS) \
	COPYING compile config.guess config.sub install-sh missing \
	ltmain.sh
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(includedir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
libopencif_la_LIBADD =
am__dirstamp = $(am__leading_dot)dirstamp
am_libopencif_la_OBJECTS = opencif/command/command.lo \
	opencif/command/controlcommand/controlcommand.lo \
	opencif/command/controlcommand/callcommand/callcommand.lo \
	opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.lo \
	opencif/command/controlcommand/definitionendcommand/definitionendcommand.lo \
	opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.lo \
	opencif/command/fraction/fraction.lo \
	opencif/command/layercommand/layercommand.lo \
	opencif/command/point/point.lo \
	opencif/command/primitivecommand/primitivecommand.lo \
	opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.lo \
	opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.lo \
	opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.lo \
	opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.lo \
	opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.lo \
	opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.lo \
	opencif/command/rawcontentcommand/rawcontentcommand.lo \
	opencif/command/rawcontentcommand/commentcommand/commentcommand.lo \
	opencif/command/rawcontentcommand/userextensioncommand/userextensioncommand.lo \
	opencif/command/size/size.lo \
	opencif/command/transformation/transformation.lo \
	opencif/file/file.lo \
	opencif/finitestatemachine/finitestatemachine.lo \
	opencif/finitestatemachine/state.lo \
	opencif/finitestatemachine/ciffsm.lo \
	opencif/command/controlcommand/endcommand/endcommand.lo
libopencif_la_OBJECTS = $(am_libopencif_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
libopencif_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(libopencif_la_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(libopencif_la_SOURCES)
DIST_SOURCES = $(libopencif_la_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
HEADERS = $(nobase_include_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/missing aclocal-1.14
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/missing autoconf
AUTOHEADER = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/missing autoheader
AUTOMAKE = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/missing automake-1.14
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FGREP = /usr/bin/grep -F
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /usr/bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = libopencif
PACKAGE_BUGREPORT = moises.chavez.martinez@gmail.com
PACKAGE_NAME = LibOpenCIF
PACKAGE_STRING = LibOpenCIF 1.0
PACKAGE_TARNAME = libopencif
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 1.0
abs_builddir = /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0
abs_srcdir = /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0
abs_top_builddir = /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0
abs_top_srcdir = /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .

# General settings
AUTOMAKE_OPTIONS = subdir-objects
lib_LTLIBRARIES = libopencif.la
libopencif_la_SOURCES = opencif/command/command.cc \
				opencif/command/controlcommand/controlcommand.cc \
				opencif/command/controlcommand/callcommand/callcommand.cc \
				opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.cc \
				opencif/command/controlcommand/definitionendcommand/definitionendcommand.cc \
				opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.cc \
				opencif/command/fraction/fraction.cc \
				opencif/command/layercommand/layercommand.cc \
				opencif/command/point/point.cc \
				opencif/command/primitivecommand/primitivecommand.cc \
				opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.cc \
				opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.cc \
				opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.cc \
				opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.cc \
				opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.cc \
				opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.cc \
				opencif/command/rawcontentcommand/rawcontentcommand.cc \
				opencif/command/rawcontentcommand/commentcommand/commentcommand.cc \
				opencif/command/rawcontentcommand/userextensioncommand/userextensioncommand.cc \
				opencif/command/size/size.cc \
				opencif/command/transformation/transformation.cc \
				opencif/file/file.cc \
				opencif/finitestatemachine/finitestatemachine.cc \
				opencif/finitestatemachine/state.cc \
				opencif/finitestatemachine/ciffsm.cc \
				opencif/command/controlcommand/endcommand/endcommand.cc

libopencif_la_LDFLAGS = -version-info 1:0:0 -all-static
nobase_include_HEADERS = opencif/opencif.h \
				opencif/command/command.h \
				opencif/command/controlcommand/controlcommand.h \
				opencif/command/controlcommand/callcommand/callcommand.h \
				opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.h \
				opencif/command/controlcommand/definitionendcommand/definitionendcommand.h \
				opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.h \
				opencif/command/fraction/fraction.h \
				opencif/command/layercommand/layercommand.h \
				opencif/command/point/point.h \
				opencif/command/primitivecommand/primitivecommand.h \
				opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.h \
				opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.h \
				opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.h \
				opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.h \
				opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.h \
				opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.h \
				opencif/command/rawcontentcommand/rawcontentcommand.h \
				opencif/command/rawcontentcommand/commentcommand/commentcommand.h \
				opencif/command/rawcontentcommand/userextensioncommand/userextensioncommand.h \
				opencif/command/size/size.h \
				opencif/command/transformation/transformation.h \
				opencif/file/file.h \
				opencif/finitestatemachine/finitestatemachine.h \
				opencif/finitestatemachine/state.h \
				opencif/finitestatemachine/ciffsm.h \
				opencif/command/controlcommand/endcommand/endcommand.h

EXTRA_DIST = doc/ \
		opencif/opencif.h \
		opencif/command/command.h \
		opencif/command/controlcommand/controlcommand.h \
		opencif/command/controlcommand/callcommand/callcommand.h \
		opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.h \
		opencif/command/controlcommand/definitionendcommand/definitionendcommand.h \
		opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.h \
		opencif/command/fraction/fraction.h \
		opencif/command/layercommand/layercommand.h \
		opencif/command/point/point.h \
		opencif/command/primitivecommand/primitivecommand.h \
		opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.h \
		opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.h \
		opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.h \
		opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.h \
		opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.h \
		opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.h \
		opencif/command/rawcontentcommand/rawcontentcommand.h \
		opencif/command/rawcontentcommand/commentcommand/commentcommand.h \
		opencif/command/rawcontentcommand/userextensioncommand/userextensioncommand.h \
		opencif/command/size/size.h \
		opencif/command/transformation/transformation.h \
		opencif/file/file.h \
		opencif/finitestatemachine/finitestatemachine.h \
		opencif/finitestatemachine/state.h \
		opencif/finitestatemachine/ciffsm.h \
		opencif/command/controlcommand/endcommand/endcommand.h \
		opencif/command/command.cc \
		opencif/command/controlcommand/controlcommand.cc \
		opencif/command/controlcommand/callcommand/callcommand.cc \
		opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.cc \
		opencif/command/controlcommand/definitionendcommand/definitionendcommand.cc \
		opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.cc \
		opencif/command/fraction/fraction.cc \
		opencif/command/layercommand/layercommand.cc \
		opencif/command/point/point.cc \
		opencif/command/primitivecommand/primitivecommand.cc \
		opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.cc \
		opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.cc \
		opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.cc \
		opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.cc \
		opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.cc \
		opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.cc \
		opencif/command/rawcontentcommand/rawcontentcommand.cc \
		opencif/command/rawcontentcommand/commentcommand/commentcommand.cc \
		opencif/command/rawcontentcommand/userextensioncommand/userextensioncommand.cc \
		opencif/command/size/size.cc \
		opencif/command/transformation/transformation.cc \
		opencif/file/file.cc \
		opencif/finitestatemachine/finitestatemachine.cc \
		opencif/finitestatemachine/state.cc \
		opencif/finitestatemachine/ciffsm.cc \
		opencif/command/controlcommand/endcommand/endcommand.cc

# Specify some flags to be passed to the compiler
# AM_CFLAGS = -I/some/include/path -L/some/lib/path

# Specify distributable binaries
# bin_PROGRAMS = test
# test_SOURCES = test.c

# Name of the static library
LDADDBASE = libopencif.la

# Specify the libraries to compile our library and the accompanying binaries (change these according to your needs)
LDADD = $(LDADDBASE)
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cc .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}
opencif/command/$(am__dirstamp):
	@$(MKDIR_P) opencif/command
	@: > opencif/command/$(am__dirstamp)
opencif/command/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/$(DEPDIR)
	@: > opencif/command/$(DEPDIR)/$(am__dirstamp)
opencif/command/command.lo: opencif/command/$(am__dirstamp) \
	opencif/command/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand
	@: > opencif/command/controlcommand/$(am__dirstamp)
opencif/command/controlcommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand/$(DEPDIR)
	@: > opencif/command/controlcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/controlcommand.lo:  \
	opencif/command/controlcommand/$(am__dirstamp) \
	opencif/command/controlcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/callcommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand/callcommand
	@: > opencif/command/controlcommand/callcommand/$(am__dirstamp)
opencif/command/controlcommand/callcommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand/callcommand/$(DEPDIR)
	@: > opencif/command/controlcommand/callcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/callcommand/callcommand.lo:  \
	opencif/command/controlcommand/callcommand/$(am__dirstamp) \
	opencif/command/controlcommand/callcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/definitiondeletecommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand/definitiondeletecommand
	@: > opencif/command/controlcommand/definitiondeletecommand/$(am__dirstamp)
opencif/command/controlcommand/definitiondeletecommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand/definitiondeletecommand/$(DEPDIR)
	@: > opencif/command/controlcommand/definitiondeletecommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.lo: opencif/command/controlcommand/definitiondeletecommand/$(am__dirstamp) \
	opencif/command/controlcommand/definitiondeletecommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/definitionendcommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand/definitionendcommand
	@: > opencif/command/controlcommand/definitionendcommand/$(am__dirstamp)
opencif/command/controlcommand/definitionendcommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand/definitionendcommand/$(DEPDIR)
	@: > opencif/command/controlcommand/definitionendcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/definitionendcommand/definitionendcommand.lo: opencif/command/controlcommand/definitionendcommand/$(am__dirstamp) \
	opencif/command/controlcommand/definitionendcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/definitionstartcommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand/definitionstartcommand
	@: > opencif/command/controlcommand/definitionstartcommand/$(am__dirstamp)
opencif/command/controlcommand/definitionstartcommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand/definitionstartcommand/$(DEPDIR)
	@: > opencif/command/controlcommand/definitionstartcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.lo: opencif/command/controlcommand/definitionstartcommand/$(am__dirstamp) \
	opencif/command/controlcommand/definitionstartcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/fraction/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/fraction
	@: > opencif/command/fraction/$(am__dirstamp)
opencif/command/fraction/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/fraction/$(DEPDIR)
	@: > opencif/command/fraction/$(DEPDIR)/$(am__dirstamp)
opencif/command/fraction/fraction.lo:  \
	opencif/command/fraction/$(am__dirstamp) \
	opencif/command/fraction/$(DEPDIR)/$(am__dirstamp)
opencif/command/layercommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/layercommand
	@: > opencif/command/layercommand/$(am__dirstamp)
opencif/command/layercommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/layercommand/$(DEPDIR)
	@: > opencif/command/layercommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/layercommand/layercommand.lo:  \
	opencif/command/layercommand/$(am__dirstamp) \
	opencif/command/layercommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/point/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/point
	@: > opencif/command/point/$(am__dirstamp)
opencif/command/point/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/point/$(DEPDIR)
	@: > opencif/command/point/$(DEPDIR)/$(am__dirstamp)
opencif/command/point/point.lo: opencif/command/point/$(am__dirstamp) \
	opencif/command/point/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand
	@: > opencif/command/primitivecommand/$(am__dirstamp)
opencif/command/primitivecommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand/$(DEPDIR)
	@: > opencif/command/primitivecommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/primitivecommand.lo:  \
	opencif/command/primitivecommand/$(am__dirstamp) \
	opencif/command/primitivecommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/pathbasedcommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand/pathbasedcommand
	@: > opencif/command/primitivecommand/pathbasedcommand/$(am__dirstamp)
opencif/command/primitivecommand/pathbasedcommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand/pathbasedcommand/$(DEPDIR)
	@: > opencif/command/primitivecommand/pathbasedcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.lo: opencif/command/primitivecommand/pathbasedcommand/$(am__dirstamp) \
	opencif/command/primitivecommand/pathbasedcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand/pathbasedcommand/polygoncommand
	@: > opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(am__dirstamp)
opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(DEPDIR)
	@: > opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.lo: opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(am__dirstamp) \
	opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand/pathbasedcommand/wirecommand
	@: > opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(am__dirstamp)
opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(DEPDIR)
	@: > opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.lo: opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(am__dirstamp) \
	opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/positionbasedcommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand/positionbasedcommand
	@: > opencif/command/primitivecommand/positionbasedcommand/$(am__dirstamp)
opencif/command/primitivecommand/positionbasedcommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand/positionbasedcommand/$(DEPDIR)
	@: > opencif/command/primitivecommand/positionbasedcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.lo: opencif/command/primitivecommand/positionbasedcommand/$(am__dirstamp) \
	opencif/command/primitivecommand/positionbasedcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand/positionbasedcommand/boxcommand
	@: > opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(am__dirstamp)
opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(DEPDIR)
	@: > opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.lo: opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(am__dirstamp) \
	opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.lo: opencif/command/primitivecommand/positionbasedcommand/$(am__dirstamp) \
	opencif/command/primitivecommand/positionbasedcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/rawcontentcommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/rawcontentcommand
	@: > opencif/command/rawcontentcommand/$(am__dirstamp)
opencif/command/rawcontentcommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/rawcontentcommand/$(DEPDIR)
	@: > opencif/command/rawcontentcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/rawcontentcommand/rawcontentcommand.lo:  \
	opencif/command/rawcontentcommand/$(am__dirstamp) \
	opencif/command/rawcontentcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/rawcontentcommand/commentcommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/rawcontentcommand/commentcommand
	@: > opencif/command/rawcontentcommand/commentcommand/$(am__dirstamp)
opencif/command/rawcontentcommand/commentcommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/rawcontentcommand/commentcommand/$(DEPDIR)
	@: > opencif/command/rawcontentcommand/commentcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/rawcontentcommand/commentcommand/commentcommand.lo: opencif/command/rawcontentcommand/commentcommand/$(am__dirstamp) \
	opencif/command/rawcontentcommand/commentcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/rawcontentcommand/userextensioncommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/rawcontentcommand/userextensioncommand
	@: > opencif/command/rawcontentcommand/userextensioncommand/$(am__dirstamp)
opencif/command/rawcontentcommand/userextensioncommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/rawcontentcommand/userextensioncommand/$(DEPDIR)
	@: > opencif/command/rawcontentcommand/userextensioncommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/rawcontentcommand/userextensioncommand/userextensioncommand.lo: opencif/command/rawcontentcommand/userextensioncommand/$(am__dirstamp) \
	opencif/command/rawcontentcommand/userextensioncommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/size/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/size
	@: > opencif/command/size/$(am__dirstamp)
opencif/command/size/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/size/$(DEPDIR)
	@: > opencif/command/size/$(DEPDIR)/$(am__dirstamp)
opencif/command/size/size.lo: opencif/command/size/$(am__dirstamp) \
	opencif/command/size/$(DEPDIR)/$(am__dirstamp)
opencif/command/transformation/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/transformation
	@: > opencif/command/transformation/$(am__dirstamp)
opencif/command/transformation/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/transformation/$(DEPDIR)
	@: > opencif/command/transformation/$(DEPDIR)/$(am__dirstamp)
opencif/command/transformation/transformation.lo:  \
	opencif/command/transformation/$(am__dirstamp) \
	opencif/command/transformation/$(DEPDIR)/$(am__dirstamp)
opencif/file/$(am__dirstamp):
	@$(MKDIR_P) opencif/file
	@: > opencif/file/$(am__dirstamp)
opencif/file/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/file/$(DEPDIR)
	@: > opencif/file/$(DEPDIR)/$(am__dirstamp)
opencif/file/file.lo: opencif/file/$(am__dirstamp) \
	opencif/file/$(DEPDIR)/$(am__dirstamp)
opencif/finitestatemachine/$(am__dirstamp):
	@$(MKDIR_P) opencif/finitestatemachine
	@: > opencif/finitestatemachine/$(am__dirstamp)
opencif/finitestatemachine/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/finitestatemachine/$(DEPDIR)
	@: > opencif/finitestatemachine/$(DEPDIR)/$(am__dirstamp)
opencif/finitestatemachine/finitestatemachine.lo:  \
	opencif/finitestatemachine/$(am__dirstamp) \
	opencif/finitestatemachine/$(DEPDIR)/$(am__dirstamp)
opencif/finitestatemachine/state.lo:  \
	opencif/finitestatemachine/$(am__dirstamp) \
	opencif/finitestatemachine/$(DEPDIR)/$(am__dirstamp)
opencif/finitestatemachine/ciffsm.lo:  \
	opencif/finitestatemachine/$(am__dirstamp) \
	opencif/finitestatemachine/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/endcommand/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand/endcommand
	@: > opencif/command/controlcommand/endcommand/$(am__dirstamp)
opencif/command/controlcommand/endcommand/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) opencif/command/controlcommand/endcommand/$(DEPDIR)
	@: > opencif/command/controlcommand/endcommand/$(DEPDIR)/$(am__dirstamp)
opencif/command/controlcommand/endcommand/endcommand.lo:  \
	opencif/command/controlcommand/endcommand/$(am__dirstamp) \
	opencif/command/controlcommand/endcommand/$(DEPDIR)/$(am__dirstamp)

libopencif.la: $(libopencif_la_OBJECTS) $(libopencif_la_DEPENDENCIES) $(EXTRA_libopencif_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libopencif_la_LINK) -rpath $(libdir) $(libopencif_la_OBJECTS) $(libopencif_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f opencif/command/*.$(OBJEXT)
	-rm -f opencif/command/*.lo
	-rm -f opencif/command/controlcommand/*.$(OBJEXT)
	-rm -f opencif/command/controlcommand/*.lo
	-rm -f opencif/command/controlcommand/callcommand/*.$(OBJEXT)
	-rm -f opencif/command/controlcommand/callcommand/*.lo
	-rm -f opencif/command/controlcommand/definitiondeletecommand/*.$(OBJEXT)
	-rm -f opencif/command/controlcommand/definitiondeletecommand/*.lo
	-rm -f opencif/command/controlcommand/definitionendcommand/*.$(OBJEXT)
	-rm -f opencif/command/controlcommand/definitionendcommand/*.lo
	-rm -f opencif/command/controlcommand/definitionstartcommand/*.$(OBJEXT)
	-rm -f opencif/command/controlcommand/definitionstartcommand/*.lo
	-rm -f opencif/command/controlcommand/endcommand/*.$(OBJEXT)
	-rm -f opencif/command/controlcommand/endcommand/*.lo
	-rm -f opencif/command/fraction/*.$(OBJEXT)
	-rm -f opencif/command/fraction/*.lo
	-rm -f opencif/command/layercommand/*.$(OBJEXT)
	-rm -f opencif/command/layercommand/*.lo
	-rm -f opencif/command/point/*.$(OBJEXT)
	-rm -f opencif/command/point/*.lo
	-rm -f opencif/command/primitivecommand/*.$(OBJEXT)
	-rm -f opencif/command/primitivecommand/*.lo
	-rm -f opencif/command/primitivecommand/pathbasedcommand/*.$(OBJEXT)
	-rm -f opencif/command/primitivecommand/pathbasedcommand/*.lo
	-rm -f opencif/command/primitivecommand/pathbasedcommand/polygoncommand/*.$(OBJEXT)
	-rm -f opencif/command/primitivecommand/pathbasedcommand/polygoncommand/*.lo
	-rm -f opencif/command/primitivecommand/pathbasedcommand/wirecommand/*.$(OBJEXT)
	-rm -f opencif/command/primitivecommand/pathbasedcommand/wirecommand/*.lo
	-rm -f opencif/command/primitivecommand/positionbasedcommand/*.$(OBJEXT)
	-rm -f opencif/command/primitivecommand/positionbasedcommand/*.lo
	-rm -f opencif/command/primitivecommand/positionbasedcommand/boxcommand/*.$(OBJEXT)
	-rm -f opencif/command/primitivecommand/positionbasedcommand/boxcommand/*.lo
	-rm -f opencif/command/rawcontentcommand/*.$(OBJEXT)
	-rm -f opencif/command/rawcontentcommand/*.lo
	-rm -f opencif/command/rawcontentcommand/commentcommand/*.$(OBJEXT)
	-rm -f opencif/command/rawcontentcommand/commentcommand/*.lo
	-rm -f opencif/command/rawcontentcommand/userextensioncommand/*.$(OBJEXT)
	-rm -f opencif/command/rawcontentcommand/userextensioncommand/*.lo
	-rm -f opencif/command/size/*.$(OBJEXT)
	-rm -f opencif/command/size/*.lo
	-rm -f opencif/command/transformation/*.$(OBJEXT)
	-rm -f opencif/command/transformation/*.lo
	-rm -f opencif/file/*.$(OBJEXT)
	-rm -f opencif/file/*.lo
	-rm -f opencif/finitestatemachine/*.$(OBJEXT)
	-rm -f opencif/finitestatemachine/*.lo

distclean-compile:
	-rm -f *.tab.c

include opencif/command/$(DEPDIR)/command.Plo
include opencif/command/controlcommand/$(DEPDIR)/controlcommand.Plo
include opencif/command/controlcommand/callcommand/$(DEPDIR)/callcommand.Plo
include opencif/command/controlcommand/definitiondeletecommand/$(DEPDIR)/definitiondeletecommand.Plo
include opencif/command/controlcommand/definitionendcommand/$(DEPDIR)/definitionendcommand.Plo
include opencif/command/controlcommand/definitionstartcommand/$(DEPDIR)/definitionstartcommand.Plo
include opencif/command/controlcommand/endcommand/$(DEPDIR)/endcommand.Plo
include opencif/command/fraction/$(DEPDIR)/fraction.Plo
include opencif/command/layercommand/$(DEPDIR)/layercommand.Plo
include opencif/command/point/$(DEPDIR)/point.Plo
include opencif/command/primitivecommand/$(DEPDIR)/primitivecommand.Plo
include opencif/command/primitivecommand/pathbasedcommand/$(DEPDIR)/pathbasedcommand.Plo
include opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(DEPDIR)/polygoncommand.Plo
include opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(DEPDIR)/wirecommand.Plo
include opencif/command/primitivecommand/positionbasedcommand/$(DEPDIR)/positionbasedcommand.Plo
include opencif/command/primitivecommand/positionbasedcommand/$(DEPDIR)/roundflashcommand.Plo
include opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(DEPDIR)/boxcommand.Plo
include opencif/command/rawcontentcommand/$(DEPDIR)/rawcontentcommand.Plo
include opencif/command/rawcontentcommand/commentcommand/$(DEPDIR)/commentcommand.Plo
include opencif/command/rawcontentcommand/userextensioncommand/$(DEPDIR)/userextensioncommand.Plo
include opencif/command/size/$(DEPDIR)/size.Plo
include opencif/command/transformation/$(DEPDIR)/transformation.Plo
include opencif/file/$(DEPDIR)/file.Plo
include opencif/finitestatemachine/$(DEPDIR)/ciffsm.Plo
include opencif/finitestatemachine/$(DEPDIR)/finitestatemachine.Plo
include opencif/finitestatemachine/$(DEPDIR)/state.Plo

.cc.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cc.lo:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf opencif/command/.libs opencif/command/_libs
	-rm -rf opencif/command/controlcommand/.libs opencif/command/controlcommand/_libs
	-rm -rf opencif/command/controlcommand/callcommand/.libs opencif/command/controlcommand/callcommand/_libs
	-rm -rf opencif/command/controlcommand/definitiondeletecommand/.libs opencif/command/controlcommand/definitiondeletecommand/_libs
	-rm -rf opencif/command/controlcommand/definitionendcommand/.libs opencif/command/controlcommand/definitionendcommand/_libs
	-rm -rf opencif/command/controlcommand/definitionstartcommand/.libs opencif/command/controlcommand/definitionstartcommand/_libs
	-rm -rf opencif/command/controlcommand/endcommand/.libs opencif/command/controlcommand/endcommand/_libs
	-rm -rf opencif/command/fraction/.libs opencif/command/fraction/_libs
	-rm -rf opencif/command/layercommand/.libs opencif/command/layercommand/_libs
	-rm -rf opencif/command/point/.libs opencif/command/point/_libs
	-rm -rf opencif/command/primitivecommand/.libs opencif/command/primitivecommand/_libs
	-rm -rf opencif/command/primitivecommand/pathbasedcommand/.libs opencif/command/primitivecommand/pathbasedcommand/_libs
	-rm -rf opencif/command/primitivecommand/pathbasedcommand/polygoncommand/.libs opencif/command/primitivecommand/pathbasedcommand/polygoncommand/_libs
	-rm -rf opencif/command/primitivecommand/pathbasedcommand/wirecommand/.libs opencif/command/primitivecommand/pathbasedcommand/wirecommand/_libs
	-rm -rf opencif/command/primitivecommand/positionbasedcommand/.libs opencif/command/primitivecommand/positionbasedcommand/_libs
	-rm -rf opencif/command/primitivecommand/positionbasedcommand/boxcommand/.libs opencif/command/primitivecommand/positionbasedcommand/boxcommand/_libs
	-rm -rf opencif/command/rawcontentcommand/.libs opencif/command/rawcontentcommand/_libs
	-rm -rf opencif/command/rawcontentcommand/commentcommand/.libs opencif/command/rawcontentcommand/commentcommand/_libs
	-rm -rf opencif/command/rawcontentcommand/userextensioncommand/.libs opencif/command/rawcontentcommand/userextensioncommand/_libs
	-rm -rf opencif/command/size/.libs opencif/command/size/_libs
	-rm -rf opencif/command/transformation/.libs opencif/command/transformation/_libs
	-rm -rf opencif/file/.libs opencif/file/_libs
	-rm -rf opencif/finitestatemachine/.libs opencif/finitestatemachine/_libs

distclean-libtool:
	-rm -f libtool config.lt
install-nobase_includeHEADERS: $(nobase_include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(includedir)" || exit 1; \
	fi; \
	$(am__nobase_list) | while read dir files; do \
	  xfiles=; for file in $$files; do \
	    if test -f "$$file"; then xfiles="$$xfiles $$file"; \
	    else xfiles="$$xfiles $(srcdir)/$$file"; fi; done; \
	  test -z "$$xfiles" || { \
	    test "x$$dir" = x. || { \
	      echo " $(MKDIR_P) '$(DESTDIR)$(includedir)/$$dir'"; \
	      $(MKDIR_P) "$(DESTDIR)$(includedir)/$$dir"; }; \
	    echo " $(INSTALL_HEADER) $$xfiles '$(DESTDIR)$(includedir)/$$dir'"; \
	    $(INSTALL_HEADER) $$xfiles "$(DESTDIR)$(includedir)/$$dir" || exit $$?; }; \
	done

uninstall-nobase_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	$(am__nobase_strip_setup); files=`$(am__nobase_strip)`; \
	dir='$(DESTDIR)$(includedir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(HEADERS) config.h
installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f opencif/command/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/callcommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/callcommand/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/definitiondeletecommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/definitiondeletecommand/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/definitionendcommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/definitionendcommand/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/definitionstartcommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/definitionstartcommand/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/endcommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/controlcommand/endcommand/$(am__dirstamp)
	-rm -f opencif/command/fraction/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/fraction/$(am__dirstamp)
	-rm -f opencif/command/layercommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/layercommand/$(am__dirstamp)
	-rm -f opencif/command/point/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/point/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/pathbasedcommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/pathbasedcommand/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/positionbasedcommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/positionbasedcommand/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(am__dirstamp)
	-rm -f opencif/command/rawcontentcommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/rawcontentcommand/$(am__dirstamp)
	-rm -f opencif/command/rawcontentcommand/commentcommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/rawcontentcommand/commentcommand/$(am__dirstamp)
	-rm -f opencif/command/rawcontentcommand/userextensioncommand/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/rawcontentcommand/userextensioncommand/$(am__dirstamp)
	-rm -f opencif/command/size/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/size/$(am__dirstamp)
	-rm -f opencif/command/transformation/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/command/transformation/$(am__dirstamp)
	-rm -f opencif/file/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/file/$(am__dirstamp)
	-rm -f opencif/finitestatemachine/$(DEPDIR)/$(am__dirstamp)
	-rm -f opencif/finitestatemachine/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf opencif/command/$(DEPDIR) opencif/command/controlcommand/$(DEPDIR) opencif/command/controlcommand/callcommand/$(DEPDIR) opencif/command/controlcommand/definitiondeletecommand/$(DEPDIR) opencif/command/controlcommand/definitionendcommand/$(DEPDIR) opencif/command/controlcommand/definitionstartcommand/$(DEPDIR) opencif/command/controlcommand/endcommand/$(DEPDIR) opencif/command/fraction/$(DEPDIR) opencif/command/layercommand/$(DEPDIR) opencif/command/point/$(DEPDIR) opencif/command/primitivecommand/$(DEPDIR) opencif/command/primitivecommand/pathbasedcommand/$(DEPDIR) opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(DEPDIR) opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(DEPDIR) opencif/command/primitivecommand/positionbasedcommand/$(DEPDIR) opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(DEPDIR) opencif/command/rawcontentcommand/$(DEPDIR) opencif/command/rawcontentcommand/commentcommand/$(DEPDIR) opencif/command/rawcontentcommand/userextensioncommand/$(DEPDIR) opencif/command/size/$(DEPDIR) opencif/command/transformation/$(DEPDIR) opencif/file/$(DEPDIR) opencif/finitestatemachine/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-nobase_includeHEADERS

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf opencif/command/$(DEPDIR) opencif/command/controlcommand/$(DEPDIR) opencif/command/controlcommand/callcommand/$(DEPDIR) opencif/command/controlcommand/definitiondeletecommand/$(DEPDIR) opencif/command/controlcommand/definitionendcommand/$(DEPDIR) opencif/command/controlcommand/definitionstartcommand/$(DEPDIR) opencif/command/controlcommand/endcommand/$(DEPDIR) opencif/command/fraction/$(DEPDIR) opencif/command/layercommand/$(DEPDIR) opencif/command/point/$(DEPDIR) opencif/command/primitivecommand/$(DEPDIR) opencif/command/primitivecommand/pathbasedcommand/$(DEPDIR) opencif/command/primitivecommand/pathbasedcommand/polygoncommand/$(DEPDIR) opencif/command/primitivecommand/pathbasedcommand/wirecommand/$(DEPDIR) opencif/command/primitivecommand/positionbasedcommand/$(DEPDIR) opencif/command/primitivecommand/positionbasedcommand/boxcommand/$(DEPDIR) opencif/command/rawcontentcommand/$(DEPDIR) opencif/command/rawcontentcommand/commentcommand/$(DEPDIR) opencif/command/rawcontentcommand/userextensioncommand/$(DEPDIR) opencif/command/size/$(DEPDIR) opencif/command/transformation/$(DEPDIR) opencif/file/$(DEPDIR) opencif/finitestatemachine/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-libLTLIBRARIES uninstall-nobase_includeHEADERS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-cscope clean-generic clean-libLTLIBRARIES clean-libtool \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-data install-data-am \
	install-dvi install-dvi-am install-exec install-exec-am \
	install-html install-html-am install-info install-info-am \
	install-libLTLIBRARIES install-man \
	install-nobase_includeHEADERS install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-libLTLIBRARIES \
	uninstall-nobase_includeHEADERS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
