# Makefile.in generated by automake 1.11.6 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__make_dryrun = \
  { \
    am__dry=no; \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        echo 'am--echo: ; @echo "AM"  OK' | $(MAKE) -f - 2>/dev/null \
          | grep '^AM OK$$' >/dev/null || am__dry=yes;; \
      *) \
        for am__flg in $$MAKEFLAGS; do \
          case $$am__flg in \
            *=*|--*) ;; \
            *n*) am__dry=yes; break;; \
          esac; \
        done;; \
    esac; \
    test $$am__dry = yes; \
  }
pkgdatadir = $(datadir)/libopencif
pkgincludedir = $(includedir)/libopencif
pkglibdir = $(libdir)/libopencif
pkglibexecdir = $(libexecdir)/libopencif
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
subdir = .
DIST_COMMON = README $(am__configure_deps) $(nobase_include_HEADERS) \
	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(srcdir)/config.h.in $(top_srcdir)/configure AUTHORS COPYING \
	ChangeLog INSTALL NEWS config.guess config.sub depcomp \
	install-sh ltmain.sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(includedir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
libopencif_la_LIBADD =
am_libopencif_la_OBJECTS = command.lo controlcommand.lo callcommand.lo \
	definitiondeletecommand.lo definitionendcommand.lo \
	definitionstartcommand.lo fraction.lo layercommand.lo point.lo \
	primitivecommand.lo pathbasedcommand.lo polygoncommand.lo \
	wirecommand.lo positionbasedcommand.lo boxcommand.lo \
	roundflashcommand.lo rawcontentcommand.lo commentcommand.lo \
	userextentioncommand.lo size.lo transformation.lo file.lo \
	finitestatemachine.lo state.lo ciffsm.lo endcommand.lo
libopencif_la_OBJECTS = $(am_libopencif_la_OBJECTS)
libopencif_la_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(libopencif_la_LDFLAGS) $(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libopencif_la_SOURCES)
DIST_SOURCES = $(libopencif_la_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
HEADERS = $(nobase_include_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AR = ar
AUTOCONF = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/missing --run autoconf
AUTOHEADER = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/missing --run autoheader
AUTOMAKE = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FGREP = /usr/bin/grep -F
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/missing --run makeinfo
MANIFEST_TOOL = :
MKDIR_P = /usr/bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = libopencif
PACKAGE_BUGREPORT = moises.chavez.martinez@gmail.com
PACKAGE_NAME = LibOpenCIF
PACKAGE_STRING = LibOpenCIF 1.0
PACKAGE_TARNAME = libopencif
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 1.0
abs_builddir = /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0
abs_srcdir = /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0
abs_top_builddir = /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0
abs_top_srcdir = /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /mnt/Cosas/Proyectos/Varios/LibOpenCIF/libopencif-1.0/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /usr/bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .

# General settings
lib_LTLIBRARIES = libopencif.la
libopencif_la_SOURCES = opencif/command/command.cc \
				opencif/command/controlcommand/controlcommand.cc \
				opencif/command/controlcommand/callcommand/callcommand.cc \
				opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.cc \
				opencif/command/controlcommand/definitionendcommand/definitionendcommand.cc \
				opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.cc \
				opencif/command/fraction/fraction.cc \
				opencif/command/layercommand/layercommand.cc \
				opencif/command/point/point.cc \
				opencif/command/primitivecommand/primitivecommand.cc \
				opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.cc \
				opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.cc \
				opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.cc \
				opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.cc \
				opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.cc \
				opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.cc \
				opencif/command/rawcontentcommand/rawcontentcommand.cc \
				opencif/command/rawcontentcommand/commentcommand/commentcommand.cc \
				opencif/command/rawcontentcommand/userextentioncommand/userextentioncommand.cc \
				opencif/command/size/size.cc \
				opencif/command/transformation/transformation.cc \
				opencif/file/file.cc \
				opencif/finitestatemachine/finitestatemachine.cc \
				opencif/finitestatemachine/state.cc \
				opencif/finitestatemachine/ciffsm.cc \
				opencif/command/controlcommand/endcommand/endcommand.cc

libopencif_la_LDFLAGS = -version-info 1:0:0 -all-static
nobase_include_HEADERS = opencif/opencif.h \
				opencif/command/command.h \
				opencif/command/controlcommand/controlcommand.h \
				opencif/command/controlcommand/callcommand/callcommand.h \
				opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.h \
				opencif/command/controlcommand/definitionendcommand/definitionendcommand.h \
				opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.h \
				opencif/command/fraction/fraction.h \
				opencif/command/layercommand/layercommand.h \
				opencif/command/point/point.h \
				opencif/command/primitivecommand/primitivecommand.h \
				opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.h \
				opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.h \
				opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.h \
				opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.h \
				opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.h \
				opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.h \
				opencif/command/rawcontentcommand/rawcontentcommand.h \
				opencif/command/rawcontentcommand/commentcommand/commentcommand.h \
				opencif/command/rawcontentcommand/userextentioncommand/userextentioncommand.h \
				opencif/command/size/size.h \
				opencif/command/transformation/transformation.h \
				opencif/file/file.h \
				opencif/finitestatemachine/finitestatemachine.h \
				opencif/finitestatemachine/state.h \
				opencif/finitestatemachine/ciffsm.h \
				opencif/command/controlcommand/endcommand/endcommand.h

EXTRA_DIST = doc/ \
		opencif/opencif.h \
		opencif/command/command.h \
		opencif/command/controlcommand/controlcommand.h \
		opencif/command/controlcommand/callcommand/callcommand.h \
		opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.h \
		opencif/command/controlcommand/definitionendcommand/definitionendcommand.h \
		opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.h \
		opencif/command/fraction/fraction.h \
		opencif/command/layercommand/layercommand.h \
		opencif/command/point/point.h \
		opencif/command/primitivecommand/primitivecommand.h \
		opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.h \
		opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.h \
		opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.h \
		opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.h \
		opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.h \
		opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.h \
		opencif/command/rawcontentcommand/rawcontentcommand.h \
		opencif/command/rawcontentcommand/commentcommand/commentcommand.h \
		opencif/command/rawcontentcommand/userextentioncommand/userextentioncommand.h \
		opencif/command/size/size.h \
		opencif/command/transformation/transformation.h \
		opencif/file/file.h \
		opencif/finitestatemachine/finitestatemachine.h \
		opencif/finitestatemachine/state.h \
		opencif/finitestatemachine/ciffsm.h \
		opencif/command/controlcommand/endcommand/endcommand.h \
		opencif/command/command.cc \
		opencif/command/controlcommand/controlcommand.cc \
		opencif/command/controlcommand/callcommand/callcommand.cc \
		opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.cc \
		opencif/command/controlcommand/definitionendcommand/definitionendcommand.cc \
		opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.cc \
		opencif/command/fraction/fraction.cc \
		opencif/command/layercommand/layercommand.cc \
		opencif/command/point/point.cc \
		opencif/command/primitivecommand/primitivecommand.cc \
		opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.cc \
		opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.cc \
		opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.cc \
		opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.cc \
		opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.cc \
		opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.cc \
		opencif/command/rawcontentcommand/rawcontentcommand.cc \
		opencif/command/rawcontentcommand/commentcommand/commentcommand.cc \
		opencif/command/rawcontentcommand/userextentioncommand/userextentioncommand.cc \
		opencif/command/size/size.cc \
		opencif/command/transformation/transformation.cc \
		opencif/file/file.cc \
		opencif/finitestatemachine/finitestatemachine.cc \
		opencif/finitestatemachine/state.cc \
		opencif/finitestatemachine/ciffsm.cc \
		opencif/command/controlcommand/endcommand/endcommand.cc

# Specify some flags to be passed to the compiler
# AM_CFLAGS = -I/some/include/path -L/some/lib/path

# Specify distributable binaries
# bin_PROGRAMS = test
# test_SOURCES = test.c

# Name of the static library
LDADDBASE = libopencif.la

# Specify the libraries to compile our library and the accompanying binaries (change these according to your needs)
LDADD = $(LDADDBASE)
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cc .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libopencif.la: $(libopencif_la_OBJECTS) $(libopencif_la_DEPENDENCIES) $(EXTRA_libopencif_la_DEPENDENCIES) 
	$(libopencif_la_LINK) -rpath $(libdir) $(libopencif_la_OBJECTS) $(libopencif_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/boxcommand.Plo
include ./$(DEPDIR)/callcommand.Plo
include ./$(DEPDIR)/ciffsm.Plo
include ./$(DEPDIR)/command.Plo
include ./$(DEPDIR)/commentcommand.Plo
include ./$(DEPDIR)/controlcommand.Plo
include ./$(DEPDIR)/definitiondeletecommand.Plo
include ./$(DEPDIR)/definitionendcommand.Plo
include ./$(DEPDIR)/definitionstartcommand.Plo
include ./$(DEPDIR)/endcommand.Plo
include ./$(DEPDIR)/file.Plo
include ./$(DEPDIR)/finitestatemachine.Plo
include ./$(DEPDIR)/fraction.Plo
include ./$(DEPDIR)/layercommand.Plo
include ./$(DEPDIR)/pathbasedcommand.Plo
include ./$(DEPDIR)/point.Plo
include ./$(DEPDIR)/polygoncommand.Plo
include ./$(DEPDIR)/positionbasedcommand.Plo
include ./$(DEPDIR)/primitivecommand.Plo
include ./$(DEPDIR)/rawcontentcommand.Plo
include ./$(DEPDIR)/roundflashcommand.Plo
include ./$(DEPDIR)/size.Plo
include ./$(DEPDIR)/state.Plo
include ./$(DEPDIR)/transformation.Plo
include ./$(DEPDIR)/userextentioncommand.Plo
include ./$(DEPDIR)/wirecommand.Plo

.cc.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cc.lo:
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

command.lo: opencif/command/command.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT command.lo -MD -MP -MF $(DEPDIR)/command.Tpo -c -o command.lo `test -f 'opencif/command/command.cc' || echo '$(srcdir)/'`opencif/command/command.cc
	$(am__mv) $(DEPDIR)/command.Tpo $(DEPDIR)/command.Plo
#	source='opencif/command/command.cc' object='command.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o command.lo `test -f 'opencif/command/command.cc' || echo '$(srcdir)/'`opencif/command/command.cc

controlcommand.lo: opencif/command/controlcommand/controlcommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT controlcommand.lo -MD -MP -MF $(DEPDIR)/controlcommand.Tpo -c -o controlcommand.lo `test -f 'opencif/command/controlcommand/controlcommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/controlcommand.cc
	$(am__mv) $(DEPDIR)/controlcommand.Tpo $(DEPDIR)/controlcommand.Plo
#	source='opencif/command/controlcommand/controlcommand.cc' object='controlcommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o controlcommand.lo `test -f 'opencif/command/controlcommand/controlcommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/controlcommand.cc

callcommand.lo: opencif/command/controlcommand/callcommand/callcommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT callcommand.lo -MD -MP -MF $(DEPDIR)/callcommand.Tpo -c -o callcommand.lo `test -f 'opencif/command/controlcommand/callcommand/callcommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/callcommand/callcommand.cc
	$(am__mv) $(DEPDIR)/callcommand.Tpo $(DEPDIR)/callcommand.Plo
#	source='opencif/command/controlcommand/callcommand/callcommand.cc' object='callcommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o callcommand.lo `test -f 'opencif/command/controlcommand/callcommand/callcommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/callcommand/callcommand.cc

definitiondeletecommand.lo: opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT definitiondeletecommand.lo -MD -MP -MF $(DEPDIR)/definitiondeletecommand.Tpo -c -o definitiondeletecommand.lo `test -f 'opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.cc
	$(am__mv) $(DEPDIR)/definitiondeletecommand.Tpo $(DEPDIR)/definitiondeletecommand.Plo
#	source='opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.cc' object='definitiondeletecommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o definitiondeletecommand.lo `test -f 'opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/definitiondeletecommand/definitiondeletecommand.cc

definitionendcommand.lo: opencif/command/controlcommand/definitionendcommand/definitionendcommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT definitionendcommand.lo -MD -MP -MF $(DEPDIR)/definitionendcommand.Tpo -c -o definitionendcommand.lo `test -f 'opencif/command/controlcommand/definitionendcommand/definitionendcommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/definitionendcommand/definitionendcommand.cc
	$(am__mv) $(DEPDIR)/definitionendcommand.Tpo $(DEPDIR)/definitionendcommand.Plo
#	source='opencif/command/controlcommand/definitionendcommand/definitionendcommand.cc' object='definitionendcommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o definitionendcommand.lo `test -f 'opencif/command/controlcommand/definitionendcommand/definitionendcommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/definitionendcommand/definitionendcommand.cc

definitionstartcommand.lo: opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT definitionstartcommand.lo -MD -MP -MF $(DEPDIR)/definitionstartcommand.Tpo -c -o definitionstartcommand.lo `test -f 'opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.cc
	$(am__mv) $(DEPDIR)/definitionstartcommand.Tpo $(DEPDIR)/definitionstartcommand.Plo
#	source='opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.cc' object='definitionstartcommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o definitionstartcommand.lo `test -f 'opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/definitionstartcommand/definitionstartcommand.cc

fraction.lo: opencif/command/fraction/fraction.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT fraction.lo -MD -MP -MF $(DEPDIR)/fraction.Tpo -c -o fraction.lo `test -f 'opencif/command/fraction/fraction.cc' || echo '$(srcdir)/'`opencif/command/fraction/fraction.cc
	$(am__mv) $(DEPDIR)/fraction.Tpo $(DEPDIR)/fraction.Plo
#	source='opencif/command/fraction/fraction.cc' object='fraction.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o fraction.lo `test -f 'opencif/command/fraction/fraction.cc' || echo '$(srcdir)/'`opencif/command/fraction/fraction.cc

layercommand.lo: opencif/command/layercommand/layercommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT layercommand.lo -MD -MP -MF $(DEPDIR)/layercommand.Tpo -c -o layercommand.lo `test -f 'opencif/command/layercommand/layercommand.cc' || echo '$(srcdir)/'`opencif/command/layercommand/layercommand.cc
	$(am__mv) $(DEPDIR)/layercommand.Tpo $(DEPDIR)/layercommand.Plo
#	source='opencif/command/layercommand/layercommand.cc' object='layercommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o layercommand.lo `test -f 'opencif/command/layercommand/layercommand.cc' || echo '$(srcdir)/'`opencif/command/layercommand/layercommand.cc

point.lo: opencif/command/point/point.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT point.lo -MD -MP -MF $(DEPDIR)/point.Tpo -c -o point.lo `test -f 'opencif/command/point/point.cc' || echo '$(srcdir)/'`opencif/command/point/point.cc
	$(am__mv) $(DEPDIR)/point.Tpo $(DEPDIR)/point.Plo
#	source='opencif/command/point/point.cc' object='point.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o point.lo `test -f 'opencif/command/point/point.cc' || echo '$(srcdir)/'`opencif/command/point/point.cc

primitivecommand.lo: opencif/command/primitivecommand/primitivecommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT primitivecommand.lo -MD -MP -MF $(DEPDIR)/primitivecommand.Tpo -c -o primitivecommand.lo `test -f 'opencif/command/primitivecommand/primitivecommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/primitivecommand.cc
	$(am__mv) $(DEPDIR)/primitivecommand.Tpo $(DEPDIR)/primitivecommand.Plo
#	source='opencif/command/primitivecommand/primitivecommand.cc' object='primitivecommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o primitivecommand.lo `test -f 'opencif/command/primitivecommand/primitivecommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/primitivecommand.cc

pathbasedcommand.lo: opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT pathbasedcommand.lo -MD -MP -MF $(DEPDIR)/pathbasedcommand.Tpo -c -o pathbasedcommand.lo `test -f 'opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.cc
	$(am__mv) $(DEPDIR)/pathbasedcommand.Tpo $(DEPDIR)/pathbasedcommand.Plo
#	source='opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.cc' object='pathbasedcommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o pathbasedcommand.lo `test -f 'opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/pathbasedcommand/pathbasedcommand.cc

polygoncommand.lo: opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT polygoncommand.lo -MD -MP -MF $(DEPDIR)/polygoncommand.Tpo -c -o polygoncommand.lo `test -f 'opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.cc
	$(am__mv) $(DEPDIR)/polygoncommand.Tpo $(DEPDIR)/polygoncommand.Plo
#	source='opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.cc' object='polygoncommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o polygoncommand.lo `test -f 'opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/pathbasedcommand/polygoncommand/polygoncommand.cc

wirecommand.lo: opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT wirecommand.lo -MD -MP -MF $(DEPDIR)/wirecommand.Tpo -c -o wirecommand.lo `test -f 'opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.cc
	$(am__mv) $(DEPDIR)/wirecommand.Tpo $(DEPDIR)/wirecommand.Plo
#	source='opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.cc' object='wirecommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o wirecommand.lo `test -f 'opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/pathbasedcommand/wirecommand/wirecommand.cc

positionbasedcommand.lo: opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT positionbasedcommand.lo -MD -MP -MF $(DEPDIR)/positionbasedcommand.Tpo -c -o positionbasedcommand.lo `test -f 'opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.cc
	$(am__mv) $(DEPDIR)/positionbasedcommand.Tpo $(DEPDIR)/positionbasedcommand.Plo
#	source='opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.cc' object='positionbasedcommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o positionbasedcommand.lo `test -f 'opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/positionbasedcommand/positionbasedcommand.cc

boxcommand.lo: opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT boxcommand.lo -MD -MP -MF $(DEPDIR)/boxcommand.Tpo -c -o boxcommand.lo `test -f 'opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.cc
	$(am__mv) $(DEPDIR)/boxcommand.Tpo $(DEPDIR)/boxcommand.Plo
#	source='opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.cc' object='boxcommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o boxcommand.lo `test -f 'opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/positionbasedcommand/boxcommand/boxcommand.cc

roundflashcommand.lo: opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT roundflashcommand.lo -MD -MP -MF $(DEPDIR)/roundflashcommand.Tpo -c -o roundflashcommand.lo `test -f 'opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.cc
	$(am__mv) $(DEPDIR)/roundflashcommand.Tpo $(DEPDIR)/roundflashcommand.Plo
#	source='opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.cc' object='roundflashcommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o roundflashcommand.lo `test -f 'opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.cc' || echo '$(srcdir)/'`opencif/command/primitivecommand/positionbasedcommand/roundflashcommand.cc

rawcontentcommand.lo: opencif/command/rawcontentcommand/rawcontentcommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT rawcontentcommand.lo -MD -MP -MF $(DEPDIR)/rawcontentcommand.Tpo -c -o rawcontentcommand.lo `test -f 'opencif/command/rawcontentcommand/rawcontentcommand.cc' || echo '$(srcdir)/'`opencif/command/rawcontentcommand/rawcontentcommand.cc
	$(am__mv) $(DEPDIR)/rawcontentcommand.Tpo $(DEPDIR)/rawcontentcommand.Plo
#	source='opencif/command/rawcontentcommand/rawcontentcommand.cc' object='rawcontentcommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o rawcontentcommand.lo `test -f 'opencif/command/rawcontentcommand/rawcontentcommand.cc' || echo '$(srcdir)/'`opencif/command/rawcontentcommand/rawcontentcommand.cc

commentcommand.lo: opencif/command/rawcontentcommand/commentcommand/commentcommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT commentcommand.lo -MD -MP -MF $(DEPDIR)/commentcommand.Tpo -c -o commentcommand.lo `test -f 'opencif/command/rawcontentcommand/commentcommand/commentcommand.cc' || echo '$(srcdir)/'`opencif/command/rawcontentcommand/commentcommand/commentcommand.cc
	$(am__mv) $(DEPDIR)/commentcommand.Tpo $(DEPDIR)/commentcommand.Plo
#	source='opencif/command/rawcontentcommand/commentcommand/commentcommand.cc' object='commentcommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o commentcommand.lo `test -f 'opencif/command/rawcontentcommand/commentcommand/commentcommand.cc' || echo '$(srcdir)/'`opencif/command/rawcontentcommand/commentcommand/commentcommand.cc

userextentioncommand.lo: opencif/command/rawcontentcommand/userextentioncommand/userextentioncommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT userextentioncommand.lo -MD -MP -MF $(DEPDIR)/userextentioncommand.Tpo -c -o userextentioncommand.lo `test -f 'opencif/command/rawcontentcommand/userextentioncommand/userextentioncommand.cc' || echo '$(srcdir)/'`opencif/command/rawcontentcommand/userextentioncommand/userextentioncommand.cc
	$(am__mv) $(DEPDIR)/userextentioncommand.Tpo $(DEPDIR)/userextentioncommand.Plo
#	source='opencif/command/rawcontentcommand/userextentioncommand/userextentioncommand.cc' object='userextentioncommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o userextentioncommand.lo `test -f 'opencif/command/rawcontentcommand/userextentioncommand/userextentioncommand.cc' || echo '$(srcdir)/'`opencif/command/rawcontentcommand/userextentioncommand/userextentioncommand.cc

size.lo: opencif/command/size/size.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT size.lo -MD -MP -MF $(DEPDIR)/size.Tpo -c -o size.lo `test -f 'opencif/command/size/size.cc' || echo '$(srcdir)/'`opencif/command/size/size.cc
	$(am__mv) $(DEPDIR)/size.Tpo $(DEPDIR)/size.Plo
#	source='opencif/command/size/size.cc' object='size.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o size.lo `test -f 'opencif/command/size/size.cc' || echo '$(srcdir)/'`opencif/command/size/size.cc

transformation.lo: opencif/command/transformation/transformation.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT transformation.lo -MD -MP -MF $(DEPDIR)/transformation.Tpo -c -o transformation.lo `test -f 'opencif/command/transformation/transformation.cc' || echo '$(srcdir)/'`opencif/command/transformation/transformation.cc
	$(am__mv) $(DEPDIR)/transformation.Tpo $(DEPDIR)/transformation.Plo
#	source='opencif/command/transformation/transformation.cc' object='transformation.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o transformation.lo `test -f 'opencif/command/transformation/transformation.cc' || echo '$(srcdir)/'`opencif/command/transformation/transformation.cc

file.lo: opencif/file/file.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT file.lo -MD -MP -MF $(DEPDIR)/file.Tpo -c -o file.lo `test -f 'opencif/file/file.cc' || echo '$(srcdir)/'`opencif/file/file.cc
	$(am__mv) $(DEPDIR)/file.Tpo $(DEPDIR)/file.Plo
#	source='opencif/file/file.cc' object='file.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o file.lo `test -f 'opencif/file/file.cc' || echo '$(srcdir)/'`opencif/file/file.cc

finitestatemachine.lo: opencif/finitestatemachine/finitestatemachine.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT finitestatemachine.lo -MD -MP -MF $(DEPDIR)/finitestatemachine.Tpo -c -o finitestatemachine.lo `test -f 'opencif/finitestatemachine/finitestatemachine.cc' || echo '$(srcdir)/'`opencif/finitestatemachine/finitestatemachine.cc
	$(am__mv) $(DEPDIR)/finitestatemachine.Tpo $(DEPDIR)/finitestatemachine.Plo
#	source='opencif/finitestatemachine/finitestatemachine.cc' object='finitestatemachine.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o finitestatemachine.lo `test -f 'opencif/finitestatemachine/finitestatemachine.cc' || echo '$(srcdir)/'`opencif/finitestatemachine/finitestatemachine.cc

state.lo: opencif/finitestatemachine/state.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT state.lo -MD -MP -MF $(DEPDIR)/state.Tpo -c -o state.lo `test -f 'opencif/finitestatemachine/state.cc' || echo '$(srcdir)/'`opencif/finitestatemachine/state.cc
	$(am__mv) $(DEPDIR)/state.Tpo $(DEPDIR)/state.Plo
#	source='opencif/finitestatemachine/state.cc' object='state.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o state.lo `test -f 'opencif/finitestatemachine/state.cc' || echo '$(srcdir)/'`opencif/finitestatemachine/state.cc

ciffsm.lo: opencif/finitestatemachine/ciffsm.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ciffsm.lo -MD -MP -MF $(DEPDIR)/ciffsm.Tpo -c -o ciffsm.lo `test -f 'opencif/finitestatemachine/ciffsm.cc' || echo '$(srcdir)/'`opencif/finitestatemachine/ciffsm.cc
	$(am__mv) $(DEPDIR)/ciffsm.Tpo $(DEPDIR)/ciffsm.Plo
#	source='opencif/finitestatemachine/ciffsm.cc' object='ciffsm.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ciffsm.lo `test -f 'opencif/finitestatemachine/ciffsm.cc' || echo '$(srcdir)/'`opencif/finitestatemachine/ciffsm.cc

endcommand.lo: opencif/command/controlcommand/endcommand/endcommand.cc
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT endcommand.lo -MD -MP -MF $(DEPDIR)/endcommand.Tpo -c -o endcommand.lo `test -f 'opencif/command/controlcommand/endcommand/endcommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/endcommand/endcommand.cc
	$(am__mv) $(DEPDIR)/endcommand.Tpo $(DEPDIR)/endcommand.Plo
#	source='opencif/command/controlcommand/endcommand/endcommand.cc' object='endcommand.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o endcommand.lo `test -f 'opencif/command/controlcommand/endcommand/endcommand.cc' || echo '$(srcdir)/'`opencif/command/controlcommand/endcommand/endcommand.cc

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt
install-nobase_includeHEADERS: $(nobase_include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(includedir)" || exit 1; \
	fi; \
	$(am__nobase_list) | while read dir files; do \
	  xfiles=; for file in $$files; do \
	    if test -f "$$file"; then xfiles="$$xfiles $$file"; \
	    else xfiles="$$xfiles $(srcdir)/$$file"; fi; done; \
	  test -z "$$xfiles" || { \
	    test "x$$dir" = x. || { \
	      echo " $(MKDIR_P) '$(DESTDIR)$(includedir)/$$dir'"; \
	      $(MKDIR_P) "$(DESTDIR)$(includedir)/$$dir"; }; \
	    echo " $(INSTALL_HEADER) $$xfiles '$(DESTDIR)$(includedir)/$$dir'"; \
	    $(INSTALL_HEADER) $$xfiles "$(DESTDIR)$(includedir)/$$dir" || exit $$?; }; \
	done

uninstall-nobase_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	$(am__nobase_strip_setup); files=`$(am__nobase_strip)`; \
	dir='$(DESTDIR)$(includedir)'; $(am__uninstall_files_from_dir)

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(HEADERS) config.h
installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-nobase_includeHEADERS

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-libLTLIBRARIES uninstall-nobase_includeHEADERS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-generic clean-libLTLIBRARIES clean-libtool ctags dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-lzma dist-shar \
	dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am \
	install-libLTLIBRARIES install-man \
	install-nobase_includeHEADERS install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-libLTLIBRARIES \
	uninstall-nobase_includeHEADERS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
